# Generated by Django 4.1.7 on 2023-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.CharField(max_length=200, verbose_name='Заказчик'),
        ),
    ]
