# Generated by Django 4.1.7 on 2023-02-17 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0002_alter_task_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='php_support.client', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='devman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='php_support.devman', verbose_name='Подрядчик'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='php_support.status', verbose_name='Статус'),
        ),
    ]
