# Generated by Django 4.1.7 on 2023-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0003_alter_task_client_alter_task_devman_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='Доступ'),
        ),
        migrations.AlterField(
            model_name='devman',
            name='is_access',
            field=models.BooleanField(default=False, verbose_name='Доступ'),
        ),
    ]
