# Generated by Django 4.1.7 on 2023-02-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0004_alter_client_is_access_alter_devman_is_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='devman',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='client',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User_id'),
        ),
        migrations.AddField(
            model_name='devman',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='User_id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='php_support.client', verbose_name='Клиент'),
        ),
    ]
