# Generated by Django 4.1.7 on 2023-02-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0005_remove_client_chat_id_remove_devman_chat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='devman',
            old_name='name',
            new_name='username',
        ),
    ]
