# Generated by Django 4.1.7 on 2023-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('php_support', '0006_rename_name_client_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pay',
            field=models.IntegerField(default=1000, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='task',
            name='questions',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы от подрядчика'),
        ),
    ]
